apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-service-deployment
  labels:
    app: car-service-deployment
spec:
  selector:
    matchLabels:
      app: car-service-deployment
  replicas: 1
  template:c
    metadata:
      labels:
        app: car-service-deployment
    spec:
      containers:
        - name: car-service
          image: ivanmisle/car-service
          ports:
            - containerPort: 8091
          env:
            - name: CONFIG_HOST
              value: config-service-service
            - name: CONFIG_PORT
              value: "8081"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_HOST_CAR
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_PORT_CAR
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_DBNAME_CAR
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_USER_CAR
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_PASSWORD_CAR
            - name: EUREKA_HOST
              value: eureka-service-service