apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-service-deploy
  labels:
    app: car-service-deploy
spec:
  selector:
    matchLabels:
      app: car-service-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app: car-service-deploy
    spec:
      containers:
        - name: car-service
          image: ivanmisle/car-service
          ports:
            - containerPort: 8095
          env:
            - name: CONFIG_HOST
              value: config-service-service
            - name: CONFIG_PORT
              value: "8081"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_HOST_CAR
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_PORT_CAR
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_DBNAME_CAR
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_USER_CAR
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_PASSWORD_CAR
            - name: EUREKA_HOST
              value: eureka-service-service
---
apiVersion: v1
kind: Service
metadata:
  name: car-service-service
  labels:
    app: car-service-service
spec:
  selector:
    app: car-service-deploy
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer
