apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service-deploy
  labels:
    app: config-service-deploy
spec:
  selector:
    matchLabels:
      app: config-service-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app: config-service-deploy
    spec:
      containers:
        - name: config-service
          image: ivanmisle/config-service
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  selector:
    app: config-service-deploy
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer