apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service-deploy
  labels:
    app: data-service-deploy
spec:
  selector:
    matchLabels:
      app: data-service-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app: data-service-deploy
    spec:
      containers:
        - name: data-service
          image: ivanmisle/data-service
          ports:
            - containerPort: 8092
          env:
            - name: CONFIG_HOST
              value: config-service-service
            - name: CONFIG_PORT
              value: "8081"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_HOST_DATA
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_PORT_DATA
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_DBNAME_DATA
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_USER_DATA
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_PASSWORD_DATA
            - name: EUREKA_HOST
              value: eureka-service-service