apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  labels:
    app: frontend-deploy
spec:
  selector:
    matchLabels:
      app: frontend-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-deploy
    spec:
      containers:
        - name: frontend
          image: ivanmisle/frontend
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-service
spec:
  selector:
    app: frontend-deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer