apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-deploy
  labels:
    app: gateway-service-deploy
spec:
  selector:
    matchLabels:
      app: gateway-service-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-service-deploy
    spec:
      containers:
        - name: gateway-service
          image: ivanmisle/gateway-service
          ports:
            - containerPort: 8090
          env:
            - name: CONFIG_HOST
              value: "config-service"
            - name: CONFIG_PORT
              value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  selector:
    app: gateway-service-deploy
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: LoadBalancer