apiVersion: apps/v1
kind: Deployment
metadata:
  name: repair-service-deploy
  labels:
    app: repair-service-deploy
spec:
  selector:
    matchLabels:
      app: repair-service-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app: repair-service-deploy
    spec:
      containers:
        - name: repair-service
          image: ivanmisle/repair-service
          ports:
            - containerPort: 8093
          env:
            - name: CONFIG_HOST
              value: config-service-service
            - name: CONFIG_PORT
              value: "8081"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_HOST_REPAIR
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_PORT_REPAIR
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_DBNAME_REPAIR
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_USER_REPAIR
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_PASSWORD_REPAIR
            - name: EUREKA_HOST
              value: eureka-service-service
